apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-management
  labels:
    app: patient-management
spec:
  replicas: 2
  selector:
    matchLabels:
      app: patient-management
  template:
    metadata:
      labels:
        app: patient-management
    spec:
      containers:
        - name: patient-management
          image: ${IMAGE}
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: staging
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"

